    /**
     * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.7.0).
     * https://openapi-generator.tech
     * Do not edit the class manually.
     */
    package at.fhtw.paperless.api;

    import org.springframework.http.ResponseEntity;
    import org.springframework.validation.annotation.Validated;
    import org.springframework.web.bind.annotation.GetMapping;
    import org.springframework.web.bind.annotation.RequestMapping;

    @Validated
    @RequestMapping("${openapi.paperless.base-path:}")
    public interface HelloworldApi {

        @GetMapping(
            value = "/helloworld",
            produces = { "text/plain" }
        )
        default ResponseEntity<String> helloworldGet(

        ) {
            return ResponseEntity.ok("Hello World!");
        }

    }
