services:
  paperless-rest:
    build: ./backend
    container_name: paperless-rest
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://paperless-db:5432/paperlessDB
    volumes:
      - maven-repo:/root/.m2
    networks:
      - app-network
    depends_on:
      paperless-db:
        condition: service_healthy
      paperless-rabbitmq:
        condition: service_started

  paperless-web:
    build: ./frontend
    container_name: paperless-web
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - paperless-rest

  paperless-db:
    image: postgres:latest
    container_name: paperless-db
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_DB: paperlessDB
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless"]
      interval: 1s
      timeout: 3s
      retries: 10

  paperless-rabbitmq:
    image: rabbitmq:management
    container_name: paperless-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - app-network

volumes:
    maven-repo:

networks:
  app-network:
    driver: bridge
