version: "3.9"

services:

  # ----------------------------------
  # Spring Boot Backend (paperless-rest)
  # ----------------------------------
  paperless-rest:
    build: ./backend
    container_name: paperless-rest
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://paperless-db:5432/paperlessDB
      - MINIO_URL=http://paperless-minio:9000
      - ELASTIC_URL=http://paperless-elasticsearch:9200
      - RABBITMQ_HOST=paperless-rabbitmq
    volumes:
      - maven-repo:/root/.m2
    networks:
      - app-network
    depends_on:
      paperless-db:
        condition: service_healthy
      paperless-rabbitmq:
        condition: service_healthy
      paperless-elasticsearch:
        condition: service_healthy

  # ----------------------------------
  # Angular Frontend (paperless-web)
  # ----------------------------------
  paperless-web:
    build: ./frontend
    container_name: paperless-web
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - paperless-rest

  # ----------------------------------
  # OCR Service (paperless-ocr)
  # ----------------------------------
  paperless-ocr:
    build: ./ocr
    container_name: paperless-ocr
    environment:
      - MINIO_URL=http://paperless-minio:9000
    volumes:
      - maven-repo:/root/.m2
    networks:
      - app-network
    depends_on:
      paperless-rabbitmq:
        condition: service_healthy
      paperless-elasticsearch:
        condition: service_healthy

  # ----------------------------------
  # PostgreSQL DB (paperless-db)
  # ----------------------------------
  paperless-db:
    image: postgres:latest
    container_name: paperless-db
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_DB: paperlessDB
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless"]
      interval: 1s
      timeout: 3s
      retries: 10

  # ----------------------------------
  # RabbitMQ (paperless-rabbitmq)
  # ----------------------------------
  paperless-rabbitmq:
    image: rabbitmq:management
    container_name: paperless-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - app-network
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 1s
      timeout: 3s
      retries: 10

  # ----------------------------------
  # MinIO (paperless-minio)
  # ----------------------------------
  paperless-minio:
    image: minio/minio:latest
    container_name: paperless-minio
    networks:
      - app-network
    volumes:
      - 'minio:/data'
    environment:
      - MINIO_ROOT_USER=paperless
      - MINIO_ROOT_PASSWORD=paperless
    command: server /data --console-address ":9090"
    ports:
      - "9000:9000"
      - "9090:9090"

  # ----------------------------------
  # Elasticsearch (paperless-elasticsearch)
  # ----------------------------------
  paperless-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: paperless-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

volumes:
  maven-repo:
  minio:

networks:
  app-network:
    driver: bridge
