services:
  backend:
    build: ./backend
    container_name: paperless-REST
    ports:
      - "8081:8081"
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/paperlessDB
    networks:
      - app-network
    depends_on:
      database:
        condition: service_healthy
      rabbitmq:
        condition: service_started

  frontend:
    build: ./frontend
    container_name: paperless-WEB
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

  database:
    image: postgres:latest
    container_name: paperless-db
    environment:
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
      POSTGRES_DB: paperlessDB
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U paperless"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:management
    container_name: paperless-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
