openapi: 3.0.3
info:
  version: "1"
  title: Paperless
servers:
  - url: http://localhost:8081
tags:
  - name: upload
  - name: search
  - name: management

paths:
  /upload:
    post:
      summary: Uploads a document
      tags:
        - upload
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                description:
                  type: string
                  example: A description for the file
              required:
                - file
      responses:
        '202':
          description: Queued for processing
        '207':
          description: The internet said so
  /helloworld:
    get:
      summary: Test response
      responses:
        '200':
          description: Hello, World!
          content:
            text/plain:
              schema:
                type: string
                example: "Hello, World!"
