openapi: 3.0.3
info:
  title: Paperless
  version: "1"
servers:
- url: http://localhost:8081
tags:
- name: upload
- name: search
- name: management
paths:
  /upload:
    post:
      requestBody:
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/_upload_post_request'
      responses:
        "202":
          description: Queued for processing
        "207":
          description: The internet said so
      summary: Uploads a document
      tags:
      - upload
      x-content-type: multipart/form-data
      x-accepts:
      - application/json
      x-tags:
      - tag: upload
  /helloworld:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                example: "Hello, World!"
                type: string
          description: "Hello, World!"
      summary: Test response
      x-accepts:
      - text/plain
components:
  schemas:
    _upload_post_request:
      properties:
        file:
          format: binary
          type: string
        description:
          example: A description for the file
          type: string
      required:
      - file
      type: object
